/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CiIA7YvXZfT
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"


export function IPInfo({ count, ip, name, text, demoMarker }: { count: number, ip: string, name: string, text: string; demoMarker?: string }) {
  const isPreview = demoMarker && demoMarker !== "production";
  return (
      <Card className="max-w-md w-full mx-4">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg font-bold">API Data</CardTitle>
            {isPreview ? (
              <span className="rounded bg-amber-100 px-2 py-0.5 text-sm font-medium text-amber-800">Preview: {demoMarker}</span>
            ) : (
              <span className="rounded bg-slate-100 px-2 py-0.5 text-sm font-medium text-slate-600">Production</span>
            )}
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <span className="font-medium">IP Address:</span>
              <span className="text-gray-500">{ip}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-medium">Count:</span>
              <span className="text-gray-500">{count}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-medium">Name:</span>
              <span className="text-gray-500">{name}</span>
            </div>
            <div className="flex items-center justify-between">
              <span className="font-medium">Text:</span>
              <span className="text-gray-500">{text}</span>
            </div>
          </div>
        </CardContent>
      </Card>  )
}
