---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/eks/apps
    repoURL: https://github.com/metalbear-co/playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
