apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-demo

resources:
  - namespace.yaml
  - fix-gateway
  - trade-feed

commonLabels:
  env: playground
  team: trading-demo
