apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: visualization-frontend-healthcheck
  namespace: visualization
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /visualization
        port: 3000
  targetRef:
    group: ""
    kind: Service
    name: visualization-frontend
