---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-visit-counter
  namespace: argocd
spec:
  source:
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: ip-visit-sqs-consumer
          patch: |-
            - op: add
              path: "/spec/template/spec/containers/0/env/-"
              value:
                name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
            - op: add
              path: "/spec/template/spec/containers/0/env/-"
              value:
                name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
            - op: add
              path: "/spec/template/spec/containers/0/env/-"
              value:
                name: AWS_DEFAULT_REGION
                value: "us-east-2"
