apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mirrord-operator-license
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mirrord-operator-license
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: mirrord-operator-license
