apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials-synced
  namespace: argocd 
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: ip-visit-aws-credentials  
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: aws-credentials 
