// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: ipinfo.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpInfoService_GetIpInfo_FullMethodName = "/ipinfo.IpInfoService/GetIpInfo"
)

// IpInfoServiceClient is the client API for IpInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpInfoServiceClient interface {
	GetIpInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*IpResponse, error)
}

type ipInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpInfoServiceClient(cc grpc.ClientConnInterface) IpInfoServiceClient {
	return &ipInfoServiceClient{cc}
}

func (c *ipInfoServiceClient) GetIpInfo(ctx context.Context, in *IpRequest, opts ...grpc.CallOption) (*IpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IpResponse)
	err := c.cc.Invoke(ctx, IpInfoService_GetIpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpInfoServiceServer is the server API for IpInfoService service.
// All implementations must embed UnimplementedIpInfoServiceServer
// for forward compatibility.
type IpInfoServiceServer interface {
	GetIpInfo(context.Context, *IpRequest) (*IpResponse, error)
	mustEmbedUnimplementedIpInfoServiceServer()
}

// UnimplementedIpInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpInfoServiceServer struct{}

func (UnimplementedIpInfoServiceServer) GetIpInfo(context.Context, *IpRequest) (*IpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIpInfo not implemented")
}
func (UnimplementedIpInfoServiceServer) mustEmbedUnimplementedIpInfoServiceServer() {}
func (UnimplementedIpInfoServiceServer) testEmbeddedByValue()                       {}

// UnsafeIpInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpInfoServiceServer will
// result in compilation errors.
type UnsafeIpInfoServiceServer interface {
	mustEmbedUnimplementedIpInfoServiceServer()
}

func RegisterIpInfoServiceServer(s grpc.ServiceRegistrar, srv IpInfoServiceServer) {
	// If the following call pancis, it indicates UnimplementedIpInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpInfoService_ServiceDesc, srv)
}

func _IpInfoService_GetIpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpInfoServiceServer).GetIpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpInfoService_GetIpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpInfoServiceServer).GetIpInfo(ctx, req.(*IpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpInfoService_ServiceDesc is the grpc.ServiceDesc for IpInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ipinfo.IpInfoService",
	HandlerType: (*IpInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIpInfo",
			Handler:    _IpInfoService_GetIpInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ipinfo.proto",
}
