// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.1
// source: ipinfo.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpRequest) Reset() {
	*x = IpRequest{}
	mi := &file_ipinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpRequest) ProtoMessage() {}

func (x *IpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ipinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpRequest.ProtoReflect.Descriptor instead.
func (*IpRequest) Descriptor() ([]byte, []int) {
	return file_ipinfo_proto_rawDescGZIP(), []int{0}
}

func (x *IpRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type IpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpResponse) Reset() {
	*x = IpResponse{}
	mi := &file_ipinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpResponse) ProtoMessage() {}

func (x *IpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ipinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpResponse.ProtoReflect.Descriptor instead.
func (*IpResponse) Descriptor() ([]byte, []int) {
	return file_ipinfo_proto_rawDescGZIP(), []int{1}
}

func (x *IpResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IpResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_ipinfo_proto protoreflect.FileDescriptor

var file_ipinfo_proto_rawDesc = string([]byte{
	0x0a, 0x0c, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x49, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x70, 0x22, 0x30, 0x0a, 0x0a, 0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x43, 0x0a, 0x0d, 0x49, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x49, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x11, 0x2e, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x49, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x49, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x62, 0x65,
	0x61, 0x72, 0x2d, 0x63, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_ipinfo_proto_rawDescOnce sync.Once
	file_ipinfo_proto_rawDescData []byte
)

func file_ipinfo_proto_rawDescGZIP() []byte {
	file_ipinfo_proto_rawDescOnce.Do(func() {
		file_ipinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ipinfo_proto_rawDesc), len(file_ipinfo_proto_rawDesc)))
	})
	return file_ipinfo_proto_rawDescData
}

var file_ipinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ipinfo_proto_goTypes = []any{
	(*IpRequest)(nil),  // 0: ipinfo.IpRequest
	(*IpResponse)(nil), // 1: ipinfo.IpResponse
}
var file_ipinfo_proto_depIdxs = []int32{
	0, // 0: ipinfo.IpInfoService.GetIpInfo:input_type -> ipinfo.IpRequest
	1, // 1: ipinfo.IpInfoService.GetIpInfo:output_type -> ipinfo.IpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ipinfo_proto_init() }
func file_ipinfo_proto_init() {
	if File_ipinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ipinfo_proto_rawDesc), len(file_ipinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ipinfo_proto_goTypes,
		DependencyIndexes: file_ipinfo_proto_depIdxs,
		MessageInfos:      file_ipinfo_proto_msgTypes,
	}.Build()
	File_ipinfo_proto = out.File
	file_ipinfo_proto_goTypes = nil
	file_ipinfo_proto_depIdxs = nil
}
