apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shop
resources:
  - ../../../manifests/shop/base/app/inventory-service
  - ../../../manifests/shop/base/app/order-service
  - ../../../manifests/shop/base/app/chat-service
  - seed-job.yaml

configMapGenerator:
  - name: catalogue-seed
    files:
      - seed-catalogue.sql

patches:
  - path: order-service-patch.yaml
    target:
      kind: Deployment
      name: order-service
