apiVersion: v1
kind: Service
metadata:
  name: visualization-frontend
  annotations:
    cloud.google.com/backend-config: '{"default":"visualization-frontend-backendconfig"}'
spec:
  selector:
    app: visualization-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
