---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-lab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci-lab
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/ci-lab
    repoURL: https://github.com/metalbear-co/playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
