apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: playground-gateway
  # Gateway can be in any namespace, placed at overlay root for shared access
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: playground.metalbear.dev
      allowedRoutes:
        namespaces:
          from: All
          # Allow HTTPRoutes from any namespace (ip-visit-counter, visualization, etc.)
      tls:
        mode: Terminate
        # Certificate is specified via pre-shared-certs in TLS options (not annotation)
        options:
          networking.gke.io/pre-shared-certs: mcrt-97fb7ff5-a06b-48d7-9bf3-4d519bdd93ef
